Add initial implementation of OpenSergo Java client
opensergo/opensergo-java-sdk pull request #1
Opened 2022-08-16 08:11 UTC by sczyh30

Add initial implementation of OpenSergo Java client.

* Add fundamental client subscribe and config cache mechanism
* Add fundamental implementation of OpenSergo gRPC client

2022-08-23 11:23 UTC, sczyh30 commented
An example of how data-plane integrates with OpenSergo Java SDK:

```java
OpenSergoClient client = new OpenSergoClient(host, port);
client.start();

// Push-model
client.subscribeConfig(new SubscribeKey(namespace, appName, configKind),
    new OpenSergoConfigSubscriber() {
        @Override
        public boolean onConfigUpdate(SubscribeKey subscribeKey, Object dataList) {
            // Handle received config here
            System.out.println("key: " + subscribeKey + ", data: " + dataList);
            return true;
        }
    });
```

2022-09-02 02:28 UTC, jnan806 requested changes

2022-09-02 02:28 UTC, jnan806 commented on src/main/proto/fault_tolerance/v1/fault_tolerance.proto
> +  string limit_mode = 3;
recommended to define enum

2022-09-02 02:28 UTC, jnan806 commented on src/main/proto/fault_tolerance/v1/fault_tolerance.proto
> +  string limit_mode = 1;
recommended to use the same enum with `limit_mode` in `RateLimitStrategy`

2022-09-02 02:28 UTC, jnan806 commented on src/main/proto/service_contract/v1/service_contract.proto
> +  reserved 4 to 16;
reserved tag conflict with docs https://github.com/opensergo/opensergo-specification/blob/main/specification/zh-Hans/README.md
maybe the docs is needed to change the tag range

<img width="783" alt="image" src="https://user-images.githubusercontent.com/43714056/188040722-c01ddd1e-2a4c-456f-bf30-09b21f62234a.png">

2022-09-02 02:28 UTC, jnan806 commented on src/main/proto/fault_tolerance/v1/fault_tolerance.proto
> +  string strategy = 1;
recommended to define an enum

2022-09-06 07:12 UTC, sczyh30 commented on src/main/proto/fault_tolerance/v1/fault_tolerance.proto
> +  string limit_mode = 1;
Good idea.

2022-09-08 10:24 UTC, jnan806 commented
是否应该将 .proto 文件抽取到 opensergo/opensergo-proto 工程

2022-09-08 13:09 UTC, sczyh30 commented
> 是否应该将 `*.proto` 文件抽取到 [opensergo/opensergo-proto](https://github.com/opensergo/opensergo-proto) 项目

对应的 proto 会提交到 opensergo-proto 项目里面；不过如何在 SDK 项目中比较方便地引用 proto，社区可以给一些更好的建议

2022-09-08 16:44 UTC, jnan806 commented
refer to [opensergo-proto` 的 [#issue 3] (https://github.com/opensergo/opensergo-proto/issues/3)

2022-09-08 17:37 UTC, jnan806 commented
> > 是否应该将 `*.proto` 文件抽取到 [opensergo/opensergo-proto](https://github.com/opensergo/opensergo-proto) 项目
> 
> 对应的 proto 会提交到 opensergo-proto 项目里面；不过如何在 SDK 项目中比较方便地引用 proto，社区可以给一些更好的建议

refer to [`opensergo/opensergo-proto` 的 issue #3](https://github.com/opensergo/opensergo-proto/issues/3)

2022-09-13 01:34 UTC, jnan806 commented
PLTA！THX.

针对 issue https://github.com/opensergo/opensergo-proto/issues/3

已经将 `grpc协议`的`java`和`go`两中SDK的依赖实现提交在 PR 中，麻烦review并且讨论下是否合理。

https://github.com/opensergo/opensergo-proto/pull/4

2022-09-25 15:28 UTC, sczyh30 commented on src/main/proto/fault_tolerance/v1/fault_tolerance.proto
> +  string limit_mode = 3;
Updated.

2022-09-25 15:30 UTC, sczyh30 commented
Hi, I've updated the latest proto and polished SDK code (a lot of bugs has been fixed...).

2022-09-25 15:46 UTC, merged

2022-09-26 02:44 UTC, jnan806 commented
ok, I've synchronized my fork branch https://github.com/jnan806/opensergo-java-sdk-review-sczyh30/tree/stubcode-based-sczyh30

2022-09-26 03:02 UTC, jnan806 commented
ok, I've synchronized my fork branch https://github.com/jnan806/opensergo-java-sdk-review-sczyh30/tree/stubcode-based-sczyh30

2022-09-26 03:02 UTC, jnan806 commented
ok, I've synchronized my fork branch https://github.com/jnan806/opensergo-java-sdk-review-sczyh30/tree/stubcode-based-sczyh30   
Please take a review